<!---
ai-eos-metadata:
  purpose: "Feature template documenting user stories, acceptance criteria, and checklist items."
  how_to_use: "Duplicate and fill out for individual features belonging to an epic."
  generated_by: "Genesis"
  regeneration: "Generated by Genesis. Instances are populated by developers."
--->

# FEATURE-000: [Feature Title]

**Epic:** [EPIC-000: Epic Title](file:///ai/epics/EPIC-000-example.md)  
**Status:** Todo / In Progress / Completed  

---

## 1. Description & User Stories
- **Description**: TODO: Summarise the feature behavior.
- **As a** ... **I want to** ... **So that** ...

## 2. Acceptance Criteria
- [ ] Criterion 1: TODO
- [ ] Criterion 2: TODO

## 3. Tasks Checklist
- [ ] [TASK-001: Task Name](file:///ai/tasks/TASK-001-example.md)
- [ ] [TASK-002: Task Name](file:///ai/tasks/TASK-002-example.md)
