<!---
ai-eos-metadata:
  purpose: "Skill guide detailing markdown editing rules and documentation formatting."
  how_to_use: "Consult when updating specs, readme, or internal project manuals."
  generated_by: "Genesis"
  regeneration: "Generated by Genesis. Customized as team conventions evolve."
--->

# Skill: Documentation Update

---

## 1. Documentation Standards

When editing markdown documentation:

- **Rule 1: Use absolute paths or clean links**: Use the target repository schemes correctly (e.g. `file:///` links).
- **Rule 2: Keep formatting clean**: Keep lines short, avoid excessive nesting, and structure headings hierarchically.
- **Rule 3: Keep it up to date**: If you change codebase structures, update the repository map.
- **Rule 4: Review before commit**: Ensure spelling is correct and markdown syntax compiles properly.

---

## 2. Document Catalog
- Core docs are located in: `ai/`
- Tasks are located in: `ai/tasks/`
- Spec templates are located in: `ai/specs/`
