<!---
ai-eos-metadata:
  purpose: "Skill guide directing safe refactoring practices and lint validations."
  how_to_use: "Consult when restructuring code modules to avoid behavioral changes."
  generated_by: "Genesis"
  regeneration: "Generated by Genesis. Customized as team conventions evolve."
--->

# Skill: Code Refactoring

---

## 1. Refactoring Rules

- **Rule 1: Keep behavioral tests green**: Run existing tests before, during, and after refactoring.
- **Rule 2: Small increments**: Do not refactor large systems in one single step. Commit small changes.
- **Rule 3: Keep docstrings & comments**: Preserve historical context unless they become obsolete.
- **Rule 4: Zero changes to public APIs**: Public interface contracts must remain unchanged.

---

## 2. Refactoring Checklist
- [ ] Code is cleaner and simpler.
- [ ] No dead code remains.
- [ ] Quality gates are passing.
