<!---
ai-eos-metadata:
  purpose: "Run summary template documenting actions, output, and validation results of a single execution loop."
  how_to_use: "Duplicate, rename with the next sequential RUN number, and fill out upon run completion."
  generated_by: "Genesis"
  regeneration: "Generated by Genesis. Instances of runs are created manually/programmatically per run."
--->

# RUN-000: [Run Goal / Name]

| Field | Value |
|---|---|
| **Run ID** | RUN-000 |
| **Date** | YYYY-MM-DD |
| **Status** | COMPLETE / FAILED |
| **Decision** | Approved / Rejected |

---

## 1. Goal
- TODO: What was the goal of this execution run?

## 2. Tasks Executed
- [ ] [TASK-001: Task Name](file:///ai/tasks/TASK-001-example.md) — Completed/Skipped
- [ ] [TASK-002: Task Name](file:///ai/tasks/TASK-002-example.md) — Completed/Skipped

## 3. Files Modified
- [MODIFY] [File Name](file:///path/to/file)
- [NEW] [File Name](file:///path/to/file)

## 4. Verification Results
- TODO: Provide command output or screenshots proving changes are correct.
